name: Build & Release

on: [push]

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set Execution Policy
        run: powershell -command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set short SHA env variable
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Built Jar
          path: build/libs/*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Velgear Experimental ${{ env.sha_short }}"
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
